2021-10-11 19:03:38 jdbc[34]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "NSERT[*] INTO CUSTOMERS (ID,NAME,PASSWORD,USERNAME)
VALUES (1, 'Imran', 'admin', 'Admin', )"; SQL statement:
NSERT INTO CUSTOMERS (ID,NAME,PASSWORD,USERNAME)
VALUES (1, 'Imran', 'admin', 'Admin', ) [42000-200]
2021-10-11 19:03:53 jdbc[34]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "CUSTOMERS" not found; SQL statement:
INSERT INTO CUSTOMERS (ID,NAME,PASSWORD,USERNAME)
VALUES (1, 'Imran', 'admin', 'Admin', ) [42102-200]
2021-10-11 19:04:06 jdbc[34]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO ADMIN (ID,NAME,PASSWORD,USERNAME)
VALUES (1, 'Imran', 'admin', 'Admin', )[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO ADMIN (ID,NAME,PASSWORD,USERNAME)
VALUES (1, 'Imran', 'admin', 'Admin', ) [42001-200]
2021-10-11 19:04:23 jdbc[34]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO ADMIN 
VALUES (1, 'Imran', 'admin', 'Admin', )[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO ADMIN 
VALUES (1, 'Imran', 'admin', 'Admin', ) [42001-200]
2021-10-11 19:04:24 jdbc[34]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO ADMIN 
VALUES (1, 'Imran', 'admin', 'Admin', )[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO ADMIN 
VALUES (1, 'Imran', 'admin', 'Admin', ) [42001-200]
2021-10-11 19:04:24 jdbc[34]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO ADMIN 
VALUES (1, 'Imran', 'admin', 'Admin', )[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO ADMIN 
VALUES (1, 'Imran', 'admin', 'Admin', ) [42001-200]
2021-10-11 19:04:25 jdbc[34]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO ADMIN 
VALUES (1, 'Imran', 'admin', 'Admin', )[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO ADMIN 
VALUES (1, 'Imran', 'admin', 'Admin', ) [42001-200]
2021-10-11 19:04:25 jdbc[34]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO ADMIN 
VALUES (1, 'Imran', 'admin', 'Admin', )[*]"; expected "DEFAULT, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
INSERT INTO ADMIN 
VALUES (1, 'Imran', 'admin', 'Admin', ) [42001-200]
2021-10-11 19:06:57 jdbc[34]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO ADMIN VALUES ('Imran Khan', 'admin, 'Admin[*]');"; SQL statement:
INSERT INTO ADMIN VALUES ('Imran Khan', 'admin, 'Admin'); [42000-200]
2021-10-11 19:07:17 jdbc[34]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO admin VALUES ('Imran Khan', 'admin, 'Admin[*]');"; SQL statement:
INSERT INTO admin VALUES ('Imran Khan', 'admin, 'Admin'); [42000-200]
2021-10-11 19:15:29 jdbc[35]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 18 more
2021-10-12 13:49:12 jdbc[26]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 18 more
